### ISSUE TITLE
Speech synthesis reads HTML out loud

### ISSUE THREAD

**Issue by shelleycooperwhite** [kennib/necsus#21]
eg. `https://chat.ncss.cloud/shelley2` try "show reminders" - will say "ull" and "lee" for `<ul>` and `<li>`.

**Comment by kennib** [comment]
You're holding it wrong, use markdown. But in all seriousness I've fixed it in commit 8a1e4af

**Comment by kennib** [comment]
You'll need to add `\n\n` between the markdown and the HTML if you use it. Hooray for markdown parsing.

**Comment by shelleycooperwhite** [comment]
Thanks Kenni! I will hold it correctly in future
