### ISSUE TITLE
Improve bot management (import, export, and grouping)

### ISSUE THREAD

**Issue by cyphar** [kennib/necsus#38]
A common issue students ran into was that they would develop a bot in its own room, and would then later have to manually copy the configuration for the bots to the "main" group room in order to do integrations. This is quite frustrating and error-prone, and if you want to make a "clone" of a room (to provide multiple demos at the same time) it's similarly frustrating.

While necsus does have a bot API which you can use to manage bots in rooms (and some tutors did write scripts to do this manually), the simplest solution might be to simply have an import/export feature for a room which would spit out some JSON that students could save somewhere and then they just have to import it into a room in order to get their bots configured.

There is a question of how to deal with bot conflicts (they imported an old version of their bots and want to import a new version, or a bot is being shared by two groups). Should we deduplicate by bot name, or ask students if there a conflicts? Or should there be a "purge on import" option to completely nuke a room before importing? I'm not sure what the best solution is. We could add some kind of folder-like "groups" for bots, so that students could export a subset of the bots in a room (or remove a subset of bots in the room). But I'm not sure whether that'd be worth the hassle of implementing -- not to mention that students would probably expect to be able to drag-and-drop bots if we have a feature like that.

**Comment by tfpk** [comment]
An alternative way to implement this feature could be a "import bots from another room" system. This would let users choose the bots they wanted, and then it would be clear if they were selecting something for overwrite. 

Otherwise, I think it shouldn't be too hard to have a "bot import wizard" that warns on duplicate bots and gives you an "accept yours/theirs" choice.

**Comment by cyphar** [comment]
The upside of there being an export option is that you get a file which you can copy around (so if someone messes up a room configuration you have an original version of the setup which worked). But you're right that a "copy from room" workflow is probably a cleaner UX.

A bot wizard probably would be a fairly simple modal to implement, though I do wonder how you'd detect duplicates (bots have names but they're not really used for anything so technically you could end up with students using the same name for two bots by accident -- though having "keep both" as an option probably solves that issue).

**Comment by tfpk** [comment]
It might be better to make the "responds to" the unique field. If you ask for two bots that expect the same prefix, you say "hey, not allowed" and ask them to pick one?

**Comment by spanishpear** [comment]
Yup - I remember enforcing that on the user side by making them pick different responds to phrases, some frontend validation could also be useful - but not a huge issue as they usually only set it up once or twice.

**Comment by cyphar** [comment]
This was don by #44. No time for grouping and I'm not sure it's worth it given the quite nice import modal Tom's cooked up.

**Comment by cyphar** [comment]
And there is absolutely no time to implement copying between rooms -- that's what clipboards are for!
