### ISSUE TITLE
Documentation loading is sometimes unsuccessful

### ISSUE THREAD

**Issue by ad-t** [kennib/necsus#4]
It has been reported that 
```
https://store.ncss.cloud/docs/
https://chat.ncss.cloud/docs/
```
do not successfully load on occasion.

**Comment by ad-t** [comment]
@kennib Are you able to replicate this behaviour?

**Comment by kennib** [comment]
I have been able to replicate it previously, but not recently. I'm not too sure what is causing this issue.
