### ISSUE TITLE
Room names with percent-encoded characters are broken

### ISSUE THREAD

**Issue by spanishpear** [kennib/necsus#55]

**Comment by spanishpear** [comment]
//TODO - test and actually check its an issue, and not a one off

**Comment by cyphar** [comment]
The issue is not with non-ASCII -- rooms with spaces have the same problem. My guess is percent-encoding is playing silly buggers (namely we are accidentally adding bots to the percent-encoded room even though we are in the non-percent encoded one, or vice versa).

**Comment by cyphar** [comment]
Message sending is also broken(?).

**Comment by cyphar** [comment]
Yeah so it looks like we're sending literal `%` signs when doing JS fetches but when our browser does things it's all in the context of the non-`%` encoded room...

**Comment by cyphar** [comment]
Fixed by fe3e7b8a2a40.
