### ISSUE TITLE
Add sensible max number of bots in a room

### ISSUE THREAD

**Issue by spanishpear** [kennib/necsus#56]

**Comment by tfpk** [comment]
Why? Also requires error handling which, like, meh.

**Comment by cyphar** [comment]
In my view the solution is two-fold:

* Kill "general".
* Have bots be collapsible in the UX (and maybe with a "collapse all" or "show all" button?).

But killing general will basically fix all of these problems.

**Comment by spanishpear** [comment]
SGTM
