### ISSUE TITLE
xss is not a feature anymore :( thanksbrowsers

### ISSUE THREAD

**Issue by spanishpear** [kennib/necsus#58]

**Comment by cyphar** [comment]
Solution is BeautifulSouping the students messages and then having some god-awful back-channel to then `eval` or some other such magic so that we can bypass Chrome's protections against XSS and pray they don't ML this workaround in the next year.

**Comment by cyphar** [comment]
I forgot we can just iterate over `script` tags and `eval` them. Thanks to Tom for reminding me that Chrome hasn't yet blocked `eval` and we could do it this much nicer way.

**Comment by cyphar** [comment]
https://github.com/ncss/necsus/commit/6312ebf33c8aa18c7a489c04b09597df2f5c5f01
