### ISSUE TITLE
changing name changes "messages sent by you" view. 

### ISSUE THREAD

**Issue by spanishpear** [kennib/necsus#59]
Ie, changing your name to anonymous in the main chatroom will show that you have sent several messagese

**Comment by tfpk** [comment]
Should be closed due to being a feature.

**Comment by cyphar** [comment]
Yeah this is kinda of a "maybe it's too much of a pain" thing -- if it's confusing then I would vote we remove left/right messages rather than implementing state that handles messages which you actually sent (long story short, it won't be fun). But I would keep them and just have this quirk just be an extension of "lol usernames can be changed whenever you like".

**Comment by cyphar** [comment]
To be clear, I had considered the whole "someone can make it look like you said it" when we originally merged the rework with left/right messages. But students already know that anyone can change their name and how the left/right thing works so I don't think it'll do any harm.

**Comment by spanishpear** [comment]
Sol: **User messages should be distinguished from bot messages.** NeCSuS is not a chatroom, its a bot room. Ie, it should be a place where one (or more) users interact with one (or more) bots. Users shouldn't be interacting with each other, so there's no real benefit from distinguishing your message, from other users messages. However, there is a benefit from distinguishing a bot's message (response) 

As of last night - conversation with @cyphar  indicated that perhaps we change the api for sending messages to add a 
`user: True` flag to messages data sent **through the client**. Bot responses wouldn't have this flag, and so would display different.

**Comment by cyphar** [comment]
That is one solution, but maybe the other solution is to ditch the left-right message view in its current form and instead do something like #42 where bot and system messages are more clearly bot or system messages.

**Comment by spanishpear** [comment]
SGTM

**Comment by spanishpear** [comment]
I think this is no longer an issue given the changes that do distinguish bot/user, also I don't really care as much about it 🤣
