### ISSUE TITLE
NeCSuS Docs == API Docs, not Interface docs. 

### ISSUE THREAD

**Issue by spanishpear** [kennib/necsus#60]
The [bot and necsus API ](https://chat.ncss.cloud/docs/) is now whats curretly being served at /docs. This is good, but also we need the documentation for rooms/adding bots/etc that currently exists at https://github.com/ncss/necsus/blob/master/README.md. 

I do think a version similar exists in grok content, but w/e

I think this /used/ to exist, but honestly cant be bothered finding where it was removed. Will fix when I get time

**Comment by cyphar** [comment]
There's a link at https://ncss.cloud/ (clearly the best sign-posted and designed ncss.cloud property). I will add a link to the sidebar at some point, or you can do it if you already know what links you'd prefer.

**Comment by spanishpear** [comment]
I didn't even know https://ncss.cloud/ existed 😆 but yup I'll add sidebar link
