### ISSUE TITLE
solve mid-air bot edit collisions

### ISSUE THREAD

**Issue by cyphar** [kennib/necsus#74]
Several students worked on the same bot regex and were confused why they overwrote each others' changes. We need to make it so that you need to actively "edit" a bot and that locks out other students from editing it.

**Comment by joelgibson** [comment]
I think that #79 addresses this, because changes to bots will be instantly visible to everyone in the chat room, so it should be easy to notice if edits are happening. I'll leave this open to see how it plays out though.
