### ISSUE TITLE
add PostgreSQL support

### ISSUE THREAD

**Issue by cyphar** [kennib/necsus#77]
When we switch to DO, it'd be nice to use a managed database rather than SQLite -- but we must keep SQLite support for students.

**Comment by joelgibson** [comment]
I'm not sure it's worth supporting any other database - SQLite means there is one less service to configure when putting it into production. It seems to handle the load just fine - after the async+websocket rewrite, the server was handling the 64-student load totally fine, using only one thread and one worker process, around 5%-10% CPU load during project time, and was snappy and responsive the whole time. Aside from that one time Andrei chucked 90MB worth of rickroll into a message.
