### ISSUE TITLE
Pick a new stylesheet or CSS solution.

### ISSUE THREAD

**Issue by joelgibson** [kennib/necsus#82]
Materialise is not good for the project because it overrides so many browser defaults - for instance, to get bullet points actually showing up on `<ul>` elements, you need to do `<ul class="browser-default">` (or lots of custom CSS).

A CSS utility class framework like Tailwind would actually work really well with how the students were using HTML this camp, my only worry is that it's heading towards learning Tailwind rather than learning CSS. Maybe this is fine (they can Inspect Element anyway to see exactly what styles are being applied).

**Comment by spanishpear** [comment]
Closed in #90
